# prefix = "demo041"
resource_group_name                  = "rg-aks-cluster-poc-5"
node_resource_group                  = "rg-aks-cluster-poc-5-managed"
resources_location                   = "westeurope"
aks_name                             = "aks-cluster"
kubernetes_version                   = "1.23.5"
acr_name                             = "acrforakstf067"
keyvault_name                        = "kvforaks067"
aks_admin_group_object_ids           = ["1eb16a7c-42cc-49e3-8ff0-d179433be6a6"] # HoussemDellaiGroup
virtual_network_address_prefix_hub   = "10.0.0.0/16"
virtual_network_address_prefix_spoke = "10.1.0.0/16"
subnet_nodes_address_prefix          = ["10.1.0.0/24"]
subnet_pods_address_prefix           = ["10.1.1.0/24"]
app_gateway_subnet_address_prefix    = ["10.0.1.0/24"]
aks_service_cidr                     = "10.0.0.0/16"
aks_dns_service_ip                   = "10.0.0.10"
aks_docker_bridge_cidr               = "172.17.0.1/16"
aks_agent_count = 2