variable "resource_group_name" {}
variable "location" {}
variable "tags" {}
variable "subscription_id" {}
variable "subnet_id" {}
variable "vm_name" {}
variable "vm_size" {}
variable "admin_username" {}
variable "admin_password" {}
variable "enable_public_ip" {}