apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-exporter
spec:
  selector:
      matchLabels:
        name: prometheus-exporter
  template:
    metadata:
      labels:
        name: prometheus-exporter
    spec:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - operator: Exists
        effect: NoExecute
      - operator: Exists
        effect: NoSchedule
      # priorityClassName: ds-priority
      containers:
      - name: prometheus-exporter
        image: us-docker.pkg.dev/google-samples/containers/gke/prometheus-dummy-exporter:v0.2.0
        command: ["./prometheus-dummy-exporter"]
        args:
        - --metric-name=custom_prometheus
        - --metric-value=40
        - --port=8080
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi